comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches:
    - 'develop'

coverage:
  status:
    project:
      default:
        threshold: 90%
    patch:
      default:
        threshold: 90%
